"""Azure OpenAI model configurations.

Deployment names match the standard OpenAI model names so that
the same model references work transparently across providers.
"""
from ..llm_provider_models import LLMInfo, ModelSize, ReasoningEffort


AZURE_OPENAI_MODELS = [
    # --- GPT-5.2 (Latest Flagship) ---
    LLMInfo(
        provider="azure_openai",
        name="gpt-5.2",
        label="GPT-5.2",
        model="gpt-5.2",  # deployment name
        description="Most capable model for professional knowledge work with thinking capabilities.",
        input_token_price=1.75,
        cached_input_token_price=0.175,
        output_token_price=14.00,
        model_icon="models/chatgpt-240.svg",
        company_icon="companies/OpenAI_logo_2025.svg",
        hosting_icon="companies/azure.svg",
        size=ModelSize.LARGE,
        max_input_tokens=272000,
        max_output_tokens=128000,
        popularity=100,
        speed=7,
        quality=9,
        best_use="General purpose",
        highlights=["Reasoning", "Images", "Tools"],
        supports_image_input=True,
        reasoning=True,
        default_reasoning_effort=ReasoningEffort.MEDIUM,
        enforced_temperature=1.0,
        default_tools=["web_search"],
        native_tools={},
    ),
    # --- GPT-5 Mini ---
    LLMInfo(
        provider="azure_openai",
        name="gpt-5-mini",
        label="GPT-5 Mini",
        model="gpt-5-mini",
        description="Fast and capable model for general chat and tool calling.",
        input_token_price=0.40,
        cached_input_token_price=0.10,
        output_token_price=1.60,
        model_icon="models/chatgpt-240.svg",
        company_icon="companies/OpenAI_logo_2025.svg",
        hosting_icon="companies/azure.svg",
        size=ModelSize.MEDIUM,
        max_input_tokens=272000,
        max_output_tokens=128000,
        popularity=85,
        speed=9,
        quality=7,
        best_use="Quick tasks",
        highlights=["Fast", "Images", "Tools"],
        supports_image_input=True,
        reasoning=True,
        default_reasoning_effort=ReasoningEffort.MEDIUM,
        enforced_temperature=1.0,
        default_tools=["web_search"],
        native_tools={},
    ),
    # --- GPT-5 Nano ---
    LLMInfo(
        provider="azure_openai",
        name="gpt-5-nano",
        label="GPT-5 Nano",
        model="gpt-5-nano",
        description="Fastest, most cost-effective model for low-latency tasks.",
        input_token_price=0.10,
        cached_input_token_price=0.025,
        output_token_price=0.40,
        model_icon="models/chatgpt-240.svg",
        company_icon="companies/OpenAI_logo_2025.svg",
        hosting_icon="companies/azure.svg",
        size=ModelSize.SMALL,
        max_input_tokens=272000,
        max_output_tokens=128000,
        popularity=60,
        speed=10,
        quality=5,
        best_use="Low-latency tasks",
        highlights=["Fastest", "Low cost"],
        reasoning=True,
        default_reasoning_effort=ReasoningEffort.MEDIUM,
        enforced_temperature=1.0,
        default_tools=["web_search"],
        native_tools={},
    ),
    # --- o4-mini (Reasoning) ---
    LLMInfo(
        provider="azure_openai",
        name="o4-mini",
        label="o4-mini",
        model="o4-mini",
        description="Fast reasoning model for complex problems.",
        input_token_price=1.10,
        cached_input_token_price=0.275,
        output_token_price=4.40,
        model_icon="models/chatgpt-240.svg",
        company_icon="companies/OpenAI_logo_2025.svg",
        hosting_icon="companies/azure.svg",
        size=ModelSize.MEDIUM,
        max_input_tokens=200000,
        max_output_tokens=100000,
        popularity=55,
        speed=7,
        quality=8,
        best_use="Reasoning",
        highlights=["Reasoning", "Tools"],
        supports_image_input=True,
        reasoning=True,
        default_reasoning_effort=ReasoningEffort.MEDIUM,
        enforced_temperature=1.0,
        default_tools=["web_search"],
    ),
]
